fix: remove public dependencies due to potential conflicts in opentelemetry-api
autotelic/fastify-opentelemetry pull request #23
Opened 2021-03-30 18:14 UTC by turneand

Potential solution for resolving the situation where multiple "opentelemetry-api" modules are loaded.
Move all "runtime" dependencies to "devDependencies".

Alternative would be to use peer dependencies, as discussed on #22

2021-03-30 20:46 UTC, HW13 requested changes
Could we try the 3rd option mentioned in #22 and use version `^0.18.0`? 

As `@opentelemetry/api` has been under rapid development, they often rename/remove/modify their exports. Most of the methods we use (eg. `getSpan`) aren't invoked until a request is received, so we'd like to provide some sort of protection from incompatible versions.

If issues still persist after that, we can try moving `@opentelemetry/api` over to `peerDependencies` 👍

2021-03-30 21:47 UTC, turneand commented
Switched out to reduce the minimum version to 0.18.0...   hopefully that'll also fix our issues.
Totally understand the issues with the opentelemetry libraries on the major changes, always a problem adopting before 1.0.
Now I just need to add unit tests to all of our services to make sure we never include more than one version of opentelemetry-api under the node_modules (or nested).

Thanks for the quick feedback on these!

2021-03-30 22:15 UTC, HW13 approved these changes
LGTM, cheers 😎 👍

2021-03-31 16:26 UTC, merged

2021-03-31 19:09 UTC, HW13 commented
Thanks for the contribution @turneand! This is now live in `v0.11.0` 🚀