fix!: use low-cardinality span name and remove serviceName option
autotelic/fastify-opentelemetry pull request #41
Opened 2021-07-28 11:00 UTC by cvrajeesh

* Use low-cardinality span name. Use `routerPath` instead of raw URL
* removed service name from the option because span name does not need to contain service name, service name should be set either on the provider or exporter.
    
  ```
  import { ResourceAttributes } from "@opentelemetry/semantic-conventions";
  import { SimpleSpanProcessor } from "@opentelemetry/tracing";
  
  .....
  const traceProvider = new NodeTracerProvider({
    resource: new Resource({
      [ResourceAttributes.SERVICE_NAME]: "myservice",
    }),
  });
  ```
    
**BREAKING CHANGE!**: service name removed from the usage and formatSpanName

Closes #40

2021-07-29 17:37 UTC, HW13 requested changes
Thanks for the contribution @cvrajeesh!

This is looking good, just a couple requests:

- The validation workflow is failing due to lint errors, could we fix those?
- Could we update the README?

2021-07-29 17:37 UTC, HW13 commented on index.js
> +  return parts.join(" ")
Could we simplify this into a ternary?

```suggestion
const { method, routerPath } = request
return routerPath ? `${method} ${routerPath}` : method
```

2021-07-31 05:20 UTC, cvrajeesh commented on index.js
> +  return parts.join(" ")
Fixed :)

2021-07-31 05:20 UTC, cvrajeesh commented
@HW13 I've made the changes please review

2021-08-09 04:57 UTC, cvrajeesh commented
@HW13 did you get a chance to review the latest changes?

2021-08-09 18:43 UTC, HW13 approved these changes
LGTM. Thanks @cvrajeesh! 😎 👍

2021-08-09 18:53 UTC, merged