Add spans to hooks
autotelic/fastify-opentelemetry pull request #57
Opened 2023-03-20 13:29 UTC by marcus13371337

Fixes:
https://github.com/autotelic/fastify-opentelemetry/issues/56

2023-09-07 11:47 UTC, marcus13371337 commented
@HW13  can you have a look? 🙏

2023-09-08 20:34 UTC, HW13 requested changes
Apologies for the delay @marcus13371337!

Thanks for the PR, this looks great! Just have a few requests 🙏

2023-09-08 20:34 UTC, HW13 commented on index.js
> +  fastify.addHook('onRequest', onRequest)
Could we use the same pattern as `onResponse` and on `onError` here as well? This way we can ensure that our `onRequest` hook always get called first

```js
fastify.addHook('onRequest', executeIfNotWrappedOrNotIgnoredRoute(onRequest))

// ...

routeOpts.onRequest = [onRequest, ...normalizeHooks(routeOpts.onRequest)]
```

2023-09-08 20:34 UTC, HW13 commented on index.js
> +      function normalizeHooks (hooks) {
Could we update this function to wrap each hook in `context`? Similar to your suggestion -> https://github.com/autotelic/fastify-opentelemetry/issues/56#issuecomment-1444841874

```js
function wrapHooks (hooks) {
  if (!hooks) {
    return []
  }

  if (Array.isArray(hooks)) {
    return hooks.map(wrapHandler)
  }

  return [wrapHandler(hooks)]
}

// Then just update remaining hook types...
routeOpts.onRequest = [onRequest, ...wrapHooks(routeOpts.onRequest)]
routeOpts.preParsing = wrapHooks(routeOpts.preParsing)
routeOpts.preValidation = wrapHooks(routeOpts.preValidation)
// ... etc.
```

2023-09-08 20:34 UTC, HW13 commented on index.js
> +      routeOpts.onError = [...normalizeHooks(routeOpts.onError), onError]
Great idea! 🧠  This will ensure we don't end our span until after all other hooks have completed

2023-09-08 20:34 UTC, HW13 commented on example/index.js
> +      activeSpan.addEvent('preValidation')
Could we have this example start and end a new span instead? Would like to show that spans from hooks are now automatically children of the plugin's span 😎

2024-03-05 20:10 UTC, HW13 commented
#65 has implemented this functionality

2024-03-05 20:10 UTC, closed without merging